services:
  backend:
    build:
      context: ./backend
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # 3000 externally, nginx runs on 80 internally
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
